#!/usr/bin/bash

echo "TODO: REPLACE BASH LOC WITH THAT OF OS1 SERVER"

gcc -g -o enc_server enc_server.c
gcc -g -o enc_client enc_client.c
gcc -g -o dec_server dec_server.c
gcc -g -o dec_client dec_client.c
gcc -g -o keygen keygen.c

# Citation: From the OS1 assignment page
